file(GLOB_RECURSE STAR_CLI_SRC_FILES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} CONFIGURE_DEPENDS "*.cc")
file(GLOB_RECURSE STAR_CLI_HDR_FILES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} CONFIGURE_DEPENDS "*.hh")

set(TARGET_NAME star_cli)
add_library(${TARGET_NAME} ${STAR_CLI_SRC_FILES} ${STAR_CLI_HDR_FILES})
set_cxx_project_standards(${TARGET_NAME} 20 FALSE)
target_include_directories(${TARGET_NAME} PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>)
target_link_libraries(${TARGET_NAME} PRIVATE star)

if(WIN32)
    target_compile_definitions(${TARGET_NAME} PRIVATE STAR_CLI_PLATFORM_WINDOWS)
    if(BUILD_SHARED_LIBS)
        target_compile_definitions(${TARGET_NAME} PRIVATE STAR_CLI_EXPORTS INTERFACE STAR_CLI_IMPORTS)
    endif()
endif()
