set(TARGET_NAME star_repl)
add_executable(${TARGET_NAME} main.cc Repl.hh Repl.cc)
target_link_libraries(${TARGET_NAME} PRIVATE star star_cli)

set_cxx_project_standards(${TARGET_NAME} 20 FALSE)
set_artifacts_dir(${TARGET_NAME} ${ARTIFACT_PREFIX})
set_msvc_target_utf8(${TARGET_NAME})
if(NOT WIN32)
    append_rpath(TARGET_NAME ${TARGET_NAME} BUILD_EXTRA_PATH ${ARTIFACT_PREFIX} INSTALL_EXTRA_PATH ${ARTIFACT_PREFIX})
endif()
