file(GLOB_RECURSE STAR_DEV_SRC_FILES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} CONFIGURE_DEPENDS "*.cc")
file(GLOB_RECURSE STAR_DEV_HDR_FILES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} CONFIGURE_DEPENDS "*.hh")

set(TARGET_NAME star_dev)
add_library(${TARGET_NAME} ${STAR_DEV_SRC_FILES} ${STAR_DEV_HDR_FILES})
set_cxx_project_standards(${TARGET_NAME} 20 FALSE)
target_include_directories(${TARGET_NAME} PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>)
target_link_libraries(${TARGET_NAME} PRIVATE star)

if(WIN32)
    target_compile_definitions(${TARGET_NAME} PRIVATE STAR_DEV_PLATFORM_WINDOWS)
    if(BUILD_SHARED_LIBS)
        target_compile_definitions(${TARGET_NAME} PRIVATE STAR_DEV_EXPORTS INTERFACE STAR_DEV_IMPORTS)
    endif()
endif()
